fn_single_line=true
format_macro_matchers=true
format_macro_bodies=false
imports_indent="Visual"
imports_layout="Horizontal"
function_arguments="Visual"
max_width=120
overflow_delimited_expr=true
where_single_line=true
