[package]
name = "arch"
version = "0.1.0"
authors = ["王子陶 <2451355023@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util={path="../util" }
jvm-core={path="../jvm-core"}
log = "0.4.0"
env_logger = "0.6.0"
